name: mindstorms api ci/cd
run-name: building and testing the mindstorms api
on: [push]
jobs:
  build-project:
    runs-on: windows-latest
    steps:
      - run: cd C:\lmdev\Ritse Spike
      - run: dir
      - run: ./gradlew build
  test-project:
    runs-on: windows-latest
    steps:
      - run: cd app
      - run: ./gradlew test
